# Generated by Django 4.1.7 on 2023-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Graduate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graduate_name", models.CharField(max_length=20)),
                ("cohort", models.CharField(max_length=20)),
                ("salary", models.IntegerField()),
                ("city", models.CharField(max_length=20)),
                ("activity", models.CharField(max_length=20)),
                ("degree_classifcation", models.CharField(max_length=20)),
            ],
        ),
    ]
